apiVersion: v1
kind: Pod
metadata:
  name: liveness-pod
spec:
  containers:
  - name: liveness-cont
    image: busybox
    command: ['sh','-c','echo hello && sleep 3600']
    livenessProbe:
      exec:
        command:
          - echo
          - testing
      initialDelaySeconds: 5
      periodSeconds: 5