apiVersion: v1
kind: Pod
metadata:
  name: multi-cp
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
  - name: busybox-c
    image: busybox
    command: ['sh','-c','while true; do sleep 30; done;']