apiVersion: v1
kind: Pod
metadata:
  name: rediness-prod
spec:
  containers:
  - name: redisness-cont
    image: nginx
    readinessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 5