apiVersion: v1
kind: Pod
metadata:
 name: resource-pod
spec:
  containers:
  - name : resource-cont
    image: busybox
    command: ['sh', '-c', 'echo me && sleep 3600']
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
       memory: "128Mi"
       cpu: "500m"
