apiVersion: v1
kind: Pod
metadata:
  name: secret-pod
spec:
  containers:
  - name : secret-container
    image: busybox
    command: ['sh','-c','echo hello && sleep 3600']
    env:
    - name: MY_PASS
      valueFrom:
        secretKeyRef:
          name: secret
          key: mykey