apiVersion: v1
kind: Pod
metadata:
  name : service-account-urolime
spec:
  serviceAccountName: urolime
  containers:
  - name: service-account-cont
    image: busybox
    command: ['sh','-c','echos hello && sleep 3600']
